_core:
  default_config_hash: gMIuS6XMaAXGl0g6aF1RHZWAez7xTIDY8quVCUmk5Eo
api_key: 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
activate_marketing_automation: false
client_key: ''
