name: Deploy to IXP Deploy Repo

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Setup Git
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Create deploy folder and clone the target repository
      - name: Clone IXP Deploy Repository
        run: |
          pwd
          ls -la
          mkdir deploy
          cd deploy
          git clone https://${{ secrets.DEPLOY_REPO_PAT }}@github.com/palcera/ixp_deploy.git .

      # Copy composer.json and composer.lock
      - name: Copy composer.json and composer.lock
        run: |
          pwd
          ls -la
          echo "Copying composer.json and composer.lock..."
          cp composer.json deploy/composer.json
          cp composer.lock deploy/composer.lock

      # Run composer install
      - name: Run Composer Install
        run: |
          echo "Running composer install..."
          composer install --working-dir=deploy

      # Copy modules/custom and themes/custom
      - name: Copy modules/custom and themes/custom
        run: |
          echo "Copying modules/custom and themes/custom..."
          [ -d deploy/web/themes/custom ] && rm -rf deploy/web/themes/custom
          cp -r web/themes/custom deploy/web/themes

      # Copy sync folder
      - name: Copy sync folder
        run: |
          echo "Copying sync folder..."
          mkdir -p deploy/config
          [ -d deploy/config/sync ] && rm -rf deploy/config/sync
          cp -r config/sync deploy/config/sync

      # Update settings.php
      - name: Update settings.php
        run: |
          cp web/sites/default/settings.php deploy/web/sites/default/settings.php

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Commit and push changes to the deploy repository
      - name: Commit and Push Changes
        run: |
          echo "Committing and pushing changes..."
          pwd
          ls -la
          cd deploy
          git add .
          git commit -m "Automated deploy update for tag $GITHUB_REF_NAME"
          git push https://${{ secrets.DEPLOY_REPO_PAT }}@github.com/palcera/ixp_deploy.git main
